import type { Metadata } from "next";
import { Inter as FontSans, Caveat as FontCursive } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactLenis } from "@/lib/react-lenis";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });
const fontCursive = FontCursive({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-cursive",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactLenis root>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased dark",
            fontSans.variable,
            fontCursive.variable
          )}
        >
          <main className="">{children}</main>
        </body>
      </html>
    </ReactLenis>
  );
}
